variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

before_script:
  - rustup component add rustfmt-preview

stages:
  - pedantry
  - clippy
  - test
  - bench

rustfmt:
  stage: pedantry
  image: "rustlang/rust:nightly"
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

cargo-deny:
  stage: pedantry
  image: "rust:1.72"
  script:
    - cargo install --locked cargo-deny
    - cargo deny check

clippy:
  stage: pedantry
  image: "rust:1.72"
  script:
    - rustup component add clippy
    - sed -i 's/\!\[warn/\!\[deny/' src/lib.rs  # deny lints
    - cargo clippy --all-features

test:features:
  stage: test
  image: rust:1.72
  script:
    - cargo install cargo-hack --locked
    - cargo hack --feature-powerset check
    - cargo test --all-features

# just make sure that the benched didn't get broken
bench:cargo-stable:
  stage: bench
  only:
    - master
  image: "rust:1.72"
  script:
    - cargo bench --no-run --features arraydist
