name: 'Check CITATION.cff for correct format'

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
    Validate-CITATION-cff:
        runs-on: ubuntu-latest
        name: Validate CITATION.cff

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Validate CITATION.cff
              uses: dieghernan/cff-validator@v3

            - name: Install Python dependencies
              run: |
                pip install cffconvert yq

            - name: Verify CITATION.cff version field
              run: |
                CITATION_VERSION=$(cffconvert -f schema.org | jq -r .version)
                RV_VERSION=$(tomlq -r .package.version Cargo.toml)
                test "$CITATION_VERSION" = "$RV_VERSION"
